{{- range $name := list "sipora-proxy" "sipora-b2bua" "sipora-edge" "sipora-lb" "sipora-api" "sipora-migrate" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ $name }}
---
{{- end }}
