FROM rust:1.95-bookworm@sha256:6084021c0c650f9764a119f04973f18cb290cbd1cd97ccc837860b6e6e5c78c4 AS builder
WORKDIR /build
RUN apt-get update && apt-get install -y --no-install-recommends \
    cmake pkg-config libcurl4-openssl-dev libsasl2-dev zlib1g-dev libssl-dev \
    && rm -rf /var/lib/apt/lists/*
COPY . .
RUN cargo build --release --bin sipora-edge

FROM gcr.io/distroless/cc-debian12:nonroot@sha256:e2d29aec8061843706b7e484c444f78fafb05bfe47745505252b1769a05d14f1
COPY --from=builder /build/target/release/sipora-edge /usr/local/bin/
EXPOSE 5061 443 5065 8080
ENTRYPOINT ["sipora-edge"]
