FROM rust:1.95-bookworm@sha256:6084021c0c650f9764a119f04973f18cb290cbd1cd97ccc837860b6e6e5c78c4 AS builder
WORKDIR /build
RUN apt-get update && apt-get install -y --no-install-recommends \
    cmake pkg-config libcurl4-openssl-dev libsasl2-dev zlib1g-dev libssl-dev \
    && rm -rf /var/lib/apt/lists/*
COPY . .
RUN cargo build --release --bin sipora-lb

FROM debian:bookworm-slim@sha256:f9c6a2fd2ddbc23e336b6257a5245e31f996953ef06cd13a59fa0a1df2d5c252
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && rm -rf /var/lib/apt/lists/*
COPY --from=builder /build/target/release/sipora-lb /usr/local/bin/
EXPOSE 5061 443 8080
ENTRYPOINT ["sipora-lb"]
