use crate::types::header::Header;
use crate::types::message::{Request, Response, SipMessage, SipVersion};
use crate::types::status::StatusCode;

/// RFC 7339 §7.2 — 503 Service Unavailable with mandatory `Retry-After`.
///
/// Every 503 generated by sipora MUST include this header so cooperating peers
/// can back off instead of hammering the overloaded proxy.
pub fn overload_response(req: &Request, retry_after_s: u32) -> SipMessage {
    let mut headers = Vec::new();
    for h in &req.headers {
        match h {
            Header::Via(_)
            | Header::From(_)
            | Header::To(_)
            | Header::CallId(_)
            | Header::CSeq(_) => headers.push(h.clone()),
            _ => {}
        }
    }
    headers.push(Header::RetryAfter(retry_after_s));
    headers.push(Header::ContentLength(0));
    SipMessage::Response(Response {
        version: SipVersion::V2_0,
        status: StatusCode::SERVICE_UNAVAILABLE,
        reason: StatusCode::SERVICE_UNAVAILABLE.reason_phrase().to_owned(),
        headers,
        body: Vec::new(),
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::header::{CSeq, NameAddr};
    use crate::types::message::SipVersion;
    use crate::types::method::Method;

    fn bare_invite() -> Request {
        Request {
            method: Method::Invite,
            uri: "sip:bob@example.com".to_owned(),
            version: SipVersion::V2_0,
            headers: vec![
                Header::From(NameAddr {
                    display_name: None,
                    uri: "sip:alice@example.com".to_owned(),
                    tag: Some("tag1".to_owned()),
                    params: vec![],
                }),
                Header::To(NameAddr {
                    display_name: None,
                    uri: "sip:bob@example.com".to_owned(),
                    tag: None,
                    params: vec![],
                }),
                Header::CallId("call-1".to_owned()),
                Header::CSeq(CSeq {
                    seq: 1,
                    method: Method::Invite,
                }),
            ],
            body: vec![],
        }
    }

    #[test]
    fn overload_response_includes_retry_after() {
        let msg = overload_response(&bare_invite(), 30);
        let SipMessage::Response(resp) = msg else {
            panic!("expected response")
        };
        assert_eq!(resp.status, StatusCode::SERVICE_UNAVAILABLE);
        let has_retry = resp
            .headers
            .iter()
            .any(|h| matches!(h, Header::RetryAfter(30)));
        assert!(has_retry, "Retry-After: 30 must be present per RFC 7339");
    }

    #[test]
    fn overload_response_copies_dialog_headers() {
        let msg = overload_response(&bare_invite(), 60);
        let SipMessage::Response(resp) = msg else {
            panic!("expected response")
        };
        assert!(resp.headers.iter().any(|h| matches!(h, Header::CallId(_))));
        assert!(resp.headers.iter().any(|h| matches!(h, Header::CSeq(_))));
    }
}
